version: '3.7'
services:
  influxdb:
    # https://hub.docker.com/r/bitnami/influxdb/
    image: quay.io/influxdb/influxdb:v2.0.3
    environment:
      INFLUXDB_ADMIN_USER: influx
      INFLUXDB_ADMIN_USER_PASSWORD: influx
      INFLUXDB_HTTP_READINESS_TIMEOUT: 30000
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - influxdb_data:/var/lib/influxdb
  psql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: coinprice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
volumes:
  influxdb_data:
    driver: local
  psql_data:
    driver: local