version: '3.7'
services:
  influxdb:
    image: docker.io/bitnami/influxdb:1-debian-10
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:
    driver: local