version: '3.7'
services:
  influxdb:
    # https://hub.docker.com/r/bitnami/influxdb/
    image: docker.io/bitnami/influxdb:1-debian-10
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - ./docker/influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:
    driver: local