version: '3.7'
services:
  influxdb:
    # https://hub.docker.com/_/influxdb
    image: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin_password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin_token
      DOCKER_INFLUXDB_INIT_ORG: coinprice
      DOCKER_INFLUXDB_INIT_BUCKET: candle
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - ./.docker/influxdb_data:/var/lib/influxdb
  psql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: coinprice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/psql_data:/var/lib/postgresql/data
volumes:
  influxdb_data:
    driver: local
  psql_data:
    driver: local